# Generated by Django 4.1.5 on 2023-02-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailynews",
            name="image",
            field=models.ImageField(default=1, upload_to="news_images"),
            preserve_default=False,
        ),
    ]
